title:       笔记本
description: Rae

theme: null

siteurl: "https://raechim.xyz/notebook"

# debug:
#   compress: true
#   dist: false
#   shortcodes: true
gittalk:
  enable:       true
  clientID:     c2e10970760af1b9be01
  clientSecret: 738136b1202a17601f65febd8e098bf3bfcb44a5
  repo:         notebook
  owner:        RaeChim
  admin:        RaeChim
  id:           comments


readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
